<?php


namespace Tir\Blog\Providers;

use Tir\Crud\Providers\CrudSeedServiceProvider;
use Tir\Blog\Database\Seeders\DatabaseSeeder;

class SeedServiceProvider extends CrudSeedServiceProvider
{
    public function boot()
    {
        $this->seeders = [
            DatabaseSeeder::class
        ];
        parent::boot(); // TODO: Change the autogenerated stub
    }
}